version: '3'
services:
  api:
    build: .
    ports:
      - "8444:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./config.yml:/app/config.yml  # Mount config file inside container
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
